### ISSUE TITLE
HTTP traffic parser

### ISSUE THREAD

**Issue by DoomTaper** [owtf/ptp#11]
since it is able to parse rankings so we should extend it to parse http traffic also because supported tools also provides their captured http traffic + we can use that traffic to run grep plugins with OWTF.

**Comment by DePierre** [comment]
@DoomTaper Could you develop a little bit further your point?

I don't understand why PTP should be parsing HTTP requests since its main goal is to parse the tools' reports.

PTP isn't a security tool on its own and won't know what to do with the HTTP traffic. What PTP is trying to do is to leverage the information already processed by the security tools in order to extract the ranks (and more).

**Comment by DePierre** [comment]
Currently implemented with 713a8fba1a402203de6ca5c02bd5e14e892ba2c3
